'use server';
/**
 * @fileOverview This file implements a Genkit flow for processing spoken user queries using the Gemini AI model.
 *
 * - processSpokenQuery - A function that handles the processing of a transcribed spoken query.
 * - ProcessSpokenQueryInput - The input type for the processSpokenQuery function.
 * - ProcessSpokenQueryOutput - The return type for the processSpokenQuery function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

/**
 * @const ProcessSpokenQueryInputSchema - Defines the input schema for the spoken query processing flow.
 * @property query - The transcribed text of the user's spoken question.
 */
const ProcessSpokenQueryInputSchema = z.object({
  query: z.string().describe('The transcribed text of the user\'s spoken question.'),
});
export type ProcessSpokenQueryInput = z.infer<typeof ProcessSpokenQueryInputSchema>;

/**
 * @const ProcessSpokenQueryOutputSchema - Defines the output schema for the spoken query processing flow.
 * @property response - The textual response generated by the AI.
 */
const ProcessSpokenQueryOutputSchema = z.object({
  response: z.string().describe('The textual response generated by the AI.'),
});
export type ProcessSpokenQueryOutput = z.infer<typeof ProcessSpokenQueryOutputSchema>;

/**
 * Processes a spoken query using the Gemini AI model.
 * @param input - An object containing the transcribed user query.
 * @returns A promise that resolves to an object containing the AI's textual response.
 */
export async function processSpokenQuery(input: ProcessSpokenQueryInput): Promise<ProcessSpokenQueryOutput> {
  return processSpokenQueryFlow(input);
}

/**
 * @const processSpokenQueryPrompt - Defines the Genkit prompt for the spoken query processing.
 * It instructs the AI (J.A.R.V.I.S) to respond to the given query.
 */
const processSpokenQueryPrompt = ai.definePrompt({
  name: 'processSpokenQueryPrompt',
  model: 'googleai/gemini-1.5-flash',
  input: {schema: ProcessSpokenQueryInputSchema},
  output: {schema: ProcessSpokenQueryOutputSchema},
  prompt: `Você é J.A.R.V.I.S, um assistente de IA por voz altamente avançado e sofisticado. Responda de forma concisa e útil à seguinte pergunta:

Pergunta: {{{query}}}`,
});

/**
 * @const processSpokenQueryFlow - Defines the Genkit flow for processing spoken queries.
 * It takes a transcribed query as input, calls the AI prompt, and returns the AI's response.
 */
const processSpokenQueryFlow = ai.defineFlow(
  {
    name: 'processSpokenQueryFlow',
    inputSchema: ProcessSpokenQueryInputSchema,
    outputSchema: ProcessSpokenQueryOutputSchema,
  },
  async (input) => {
    const {output} = await processSpokenQueryPrompt(input);
    if (!output) {
      throw new Error('AI did not return a response.');
    }
    return output;
  }
);
